# Generated by Django 5.1.3 on 2026-02-21 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_score', models.FloatField()),
                ('rubric_version', models.TextField()),
                ('notes', models.TextField(null=True)),
                ('created_at', models.TextField()),
            ],
            options={
                'db_table': 'assessments',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Comparison',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rubric_document_id', models.IntegerField()),
                ('candidate_document_id', models.IntegerField()),
                ('mode', models.TextField()),
                ('model', models.TextField()),
                ('threshold_strong', models.FloatField()),
                ('threshold_partial', models.FloatField()),
                ('strong_count', models.IntegerField()),
                ('partial_count', models.IntegerField()),
                ('missing_count', models.IntegerField()),
                ('overall_score', models.FloatField()),
                ('created_at', models.TextField()),
            ],
            options={
                'db_table': 'comparisons',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('building_type', models.TextField()),
                ('address', models.TextField(null=True)),
                ('created_at', models.TextField()),
            ],
            options={
                'db_table': 'projects',
                'managed': False,
            },
        ),
    ]
