# Generated by Django 5.1.3 on 2026-02-21 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(null=True)),
                ('address', models.TextField(null=True)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('source_doc', models.TextField(null=True)),
                ('created_at', models.TextField()),
            ],
            options={
                'db_table': 'locations',
                'managed': False,
            },
        ),
    ]
