# Generated by Django 5.1.3 on 2026-02-21 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChunkMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comparison', models.IntegerField()),
                ('rubric_chunk_id', models.IntegerField()),
                ('candidate_chunk_id', models.IntegerField(null=True)),
                ('similarity', models.FloatField()),
                ('status', models.TextField()),
                ('rubric_path', models.TextField(null=True)),
                ('candidate_path', models.TextField(null=True)),
                ('rubric_excerpt', models.TextField(null=True)),
                ('candidate_excerpt', models.TextField(null=True)),
            ],
            options={
                'db_table': 'chunk_matches',
                'managed': False,
            },
        ),
    ]
